export enum EventType {
  USER_CREATED = "user.created",
  USER_UPDATED = "user.updated",
  USER_DELETED = "user.deleted",
  AUTH_REFRESH = "auth.refresh",
  AUTH_LOGIN = "auth.login",
  AUTH_LOGIN_OAUTH = "auth.login_oauth",
  AUTH_LOGIN_BACKUP_CODE = "auth.login_backupCode",
  AUTH_LOGIN_GOOGLE = "auth.login_google",
  AUTH_PASSWORD_CHANGED = "auth.password_changed",
  AUTH_PASSWORD_RESET_REQUESTED = "auth.passwordReset",
  AUTH_APPROVE_LOCATION = "auth.approveLocation",
  ORGANIZATION_CREATED = "group.created",
  ORGANIZATION_UPDATED = "group.updated",
  ORGANIZATION_DELETED = "group.deleted",
  EMAIL_CREATED = "email.created",
  EMAIL_UPDATED = "email.updated",
  EMAIL_DELETED = "email.deleted",
  EMAIL_VERIFIED = "email.verified",
  MEMBERSHIP_CREATED = "membership.created",
  MEMBERSHIP_UPDATED = "membership.updated",
  MEMBERSHIP_DELETED = "membership.deleted",
  BILLING_UPDATED = "billing.updated",
  API_KEY_CREATED = "apiKey.created",
  API_KEY_UPDATED = "apiKey.updated",
  API_KEY_DELETED = "apiKey.deleted",
}

export enum Templates {
  EMAIL_VERIFY = "email-verify",
  PASSWORD_RESET = "password-reset",
  NEW_PASSWORD = "new-password",
  INVITED_TO_TEAM = "invited",
  UNAPPROVED_LOCATION = "unapproved-location",
  CREDITS_NEW_USER = "credits-new-user",
  CREDITS_INVITED_BY = "credits-invited-by",
  LOGIN_LINK = "login-link",
}

export enum Tokens {
  LOGIN = "auth",
  LOGIN_LINK = "login-link",
  API_KEY = "api-key",
  ACCESS_TOKEN = "access-token",
  TWO_FACTOR = "2fa",
  REFRESH = "refresh",
  PASSWORD_RESET = "password-reset",
  EMAIL_VERIFY = "email-verify",
  EMAIL_RESEND = "email-resend",
  APPROVE_LOCATION = "approve-location",
  COUPON = "coupon",
}

export enum Webhooks {
  ALL_EVENTS = "*",
  UPDATE_ORGANIZATION = "update-group",
  DELETE_ORGANIZATION = "delete-group",
  UPDATE_ORGANIZATION_BILLING = "update-group-billing",
  UPDATE_ORGANIZATION_SUBSCRIPTION = "update-group-subscription",
  CREATE_ORGANIZATION_SUBSCRIPTION = "create-group-subscription",
  DELETE_ORGANIZATION_SOURCE = "delete-group-source",
  UPDATE_ORGANIZATION_SOURCE = "update-group-source",
  CREATE_ORGANIZATION_SOURCE = "create-group-source",
  UPDATE_API_KEY = "update-api-key",
  CREATE_API_KEY = "create-api-key",
  DELETE_API_KEY = "delete-api-key",
  UPDATE_DOMAIN = "update-domain",
  CREATE_DOMAIN = "create-domain",
  DELETE_DOMAIN = "delete-domain",
  VERIFY_DOMAIN = "verify-domain",
  TEST_WEBHOOK = "test-webhook",
  UPDATE_WEBHOOK = "update-webhook",
  CREATE_WEBHOOK = "create-webhook",
  DELETE_WEBHOOK = "delete-webhook",
}
