@baseUrl = http://localhost:3000/v1
@userId = 1

POST {{baseUrl}}/users/{{userId}}/memberships
content-type: application/json
Authorization: Bearer {{$dotenv HTTP_TEST_ACCESS_TOKEN}}

{
  "name": "Koj"
}
