@baseUrl = http://localhost:3000/v1
@groupId = 1

POST {{baseUrl}}/groups/{{groupId}}/api-keys
content-type: application/json
Authorization: Bearer {{$dotenv HTTP_TEST_ACCESS_TOKEN}}

{
  "scopes": ["group-1:*"]
}
