@baseUrl = http://localhost:3000/v1

POST {{baseUrl}}/auth/reset-password
content-type: application/json

{
  "token": "{{$dotenv PASSWORD_RESET_TOKEN}}",
  "password": "{{$dotenv HTTP_TEST_PASSWORD}}"
}
