export const MULTI_FACTOR_TOKEN = 'MULTI_FACTOR_TOKEN';
export const PASSWORD_RESET_TOKEN = 'PASSWORD_RESET_TOKEN';
export const EMAIL_VERIFY_TOKEN = 'EMAIL_VERIFY_TOKEN';
export const APPROVE_SUBNET_TOKEN = 'APPROVE_SUBNET_TOKEN';
export const EMAIL_MFA_TOKEN = 'EMAIL_MFA_TOKEN';
